stages:
    - debug
    - release
    - documentation


variables:
  DOCKER_DRIVER: overlay


cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true
  paths:
    - $CI_PROJECT_DIR/cache


.base_gnu:
  before_script: 
    - source /opt/intel/mkl/bin/mklvars.sh intel64 
    - FORTRAN_EXTRA_FLAGS="-DFORTRAN_EXTRA_FLAGS=-fimplicit-none"
    - ROOT_DIR=$CI_PROJECT_DIR
    - BUILD_DIR=/data/BUILD
    - FEMPAR_DIR=$BUILD_DIR/FEMPAR
    - mkdir -p $FEMPAR_DIR
    - cd $ROOT_DIR
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - ln -sf CMake/CTestConfig_CIMNE.cmake CTestConfig.cmake


.base_intel:
   before_script: 
    - source /usr/local/Modules/init/bash 
    - FORTRAN_EXTRA_FLAGS="-DFORTRAN_EXTRA_FLAGS=-implicitnone"
    - ROOT_DIR=$CI_PROJECT_DIR
    - BUILD_DIR=$ROOT_DIR/BUILD
    - FEMPAR_DIR=$BUILD_DIR/FEMPAR
    - mkdir -p $FEMPAR_DIR
    - cd $ROOT_DIR
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - ln -sf CMake/CTestConfig_CIMNE.cmake CTestConfig.cmake


.script_template:
  script: &script_template
    - $LOAD_ENV_COMMAND
    - mkdir -p $THIRDPARTY_DIR
    - cd $THIRDPARTY_DIR
    - for library in FPL F3PHT FLAP VTKIO SISL XH5For FortranParser
      do
        mkdir -p $THIRDPARTY_DIR/$library
        cd $THIRDPARTY_DIR/$library
        cmake -DCMAKE_BUILD_TYPE=$BUILD_MODE $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty/$library
        cmake --build . -- -j8
      done
    - cd $FEMPAR_DIR
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_MODE -DFEMPAR_BUILD_LABEL=$TEST_LABEL -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -j8 -V -L $TEST_LABEL -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest $EXTRA_DASHBOARDS -D ExperimentalSubmit
    - tests_passed=0
    - test -f $FEMPAR_DIR/Testing/Temporary/LastTestsFailed*.log && tests_passed=1
    - ls -l $FEMPAR_DIR/Testing/Temporary/LastTestsFailed*.log
    - cat $FEMPAR_DIR/Testing/Temporary/LastTestsFailed*.log  
    - set -e
    - echo $tests_passed
    - test $tests_passed -eq 0


GNU_DEBUG_P4EST_SERIAL:
  image: fempar/fempar-env:gnu-debug_p4est-serial
  stage: debug
  tags:
    - test-ci
  only:
    - merge_requests
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    BUILD_MODE: DEBUG
    TEST_LABEL: SERIAL
  script: *script_template
  
  
GNU_DEBUG_P4EST_SERIAL_MEM_COV:
  image: fempar/fempar-env:gnu-debug_p4est-serial
  stage: debug
  tags:
    - test-ci
  only:
    - experimental
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    BUILD_MODE: DEBUG
    TEST_LABEL: SERIAL
    EXTRA_DASHBOARDS: "-D ExperimentalCoverage -D ExperimentalMemCheck"
  script: *script_template


GNU_DEBUG_P4EST_SERIAL_FAST:
  image: fempar/fempar-env:gnu-debug_p4est-serial
  stage: debug
  tags:
    - test-ci
  except:
    - experimental
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    BUILD_MODE: DEBUG
    TEST_LABEL: SERIAL_FAST
  script: *script_template


GNU_DEBUG_P4EST_PARALLEL:
  image: fempar/fempar-env:gnu-debug_p4est-parallel
  stage: debug
  tags:
    - test-ci
  only:
    - merge_requests
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    BUILD_MODE: DEBUG
    TEST_LABEL: PARALLEL
  script: *script_template
  

GNU_DEBUG_P4EST_PARALLEL_MEM_COV:
  image: fempar/fempar-env:gnu-debug_p4est-parallel
  stage: debug
  tags:
    - test-ci
  only:
    - experimental
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    BUILD_MODE: DEBUG
    TEST_LABEL: PARALLEL
    EXTRA_DASHBOARDS: "-D ExperimentalCoverage -D ExperimentalMemCheck"
  script: *script_template


GNU_DEBUG_P4EST_PARALLEL_FAST:
  image: fempar/fempar-env:gnu-debug_p4est-parallel
  stage: debug
  tags:
    - test-ci
  except:
    - experimental
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    BUILD_MODE: DEBUG
    TEST_LABEL: PARALLEL_FAST
  script: *script_template


GNU_RELEASE_P4EST_SERIAL:
  image: fempar/fempar-env:gnu-release_p4est-serial
  stage: release
  tags:
    - test-ci
  only:
    - experimental
    - merge_requests
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/release/THIRDPARTY
    BUILD_MODE: RELEASE
    TEST_LABEL: SERIAL
  script: *script_template


GNU_RELEASE_P4EST_SERIAL_FAST:
  image: fempar/fempar-env:gnu-release_p4est-serial
  stage: release
  tags:
    - test-ci
  except:
    - experimental
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/release/THIRDPARTY
    BUILD_MODE: RELEASE
    TEST_LABEL: SERIAL_FAST
  script: *script_template


GNU_RELEASE_P4EST_PARALLEL:
  image: fempar/fempar-env:gnu-release_p4est-parallel
  stage: release
  tags:
    - test-ci
  only:
    - experimental
    - merge_requests
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/release/THIRDPARTY
    BUILD_MODE: RELEASE
    TEST_LABEL: PARALLEL
  script: *script_template


GNU_RELEASE_P4EST_PARALLEL_FAST:
  image: fempar/fempar-env:gnu-release_p4est-parallel
  stage: release
  tags:
    - test-ci
  except:
    - experimental
  extends: .base_gnu
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/gnu/release/THIRDPARTY
    BUILD_MODE: RELEASE
    TEST_LABEL: PARALLEL_FAST
  script: *script_template


INTEL_RELEASE_P4EST_SERIAL:
  image: registry.gitlab.com/fempar/fempar-beta:latest
  stage: release
  tags:
    - test-ci
  only:
    - experimental
    - merge_requests
  extends: .base_intel
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/intel/release/THIRDPARTY
    BUILD_MODE: RELEASE
    TEST_LABEL: SERIAL
    LOAD_ENV_COMMAND: module load INTEL_SERIAL
  script: *script_template


INTEL_RELEASE_P4EST_SERIAL_FAST:
  image: registry.gitlab.com/fempar/fempar-beta:latest
  stage: release
  when: always
  tags:
    - test-ci
  except:
    - experimental
  extends: .base_intel
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/intel/release/THIRDPARTY
    BUILD_MODE: RELEASE
    TEST_LABEL: SERIAL_FAST
    LOAD_ENV_COMMAND: module load INTEL_SERIAL
  script: *script_template


INTEL_RELEASE_P4EST_PARALLEL:
  image: registry.gitlab.com/fempar/fempar-beta:latest
  stage: release
  when: always
  tags:
    - test-ci
  only:
    - experimental
    - merge_requests
  extends: .base_intel
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/intel/release/THIRDPARTY
    BUILD_MODE: RELEASE
    TEST_LABEL: PARALLEL
    LOAD_ENV_COMMAND: module load INTEL_PARALLEL
  script: *script_template


INTEL_RELEASE_P4EST_PARALLEL_FAST:
  image: registry.gitlab.com/fempar/fempar-beta:latest
  stage: release
  when: always
  tags:
    - test-ci
  except:
    - experimental
  extends: .base_intel
  variables:
    THIRDPARTY_DIR: $CI_PROJECT_DIR/cache/intel/release/THIRDPARTY
    BUILD_MODE: RELEASE
    TEST_LABEL: PARALLEL_FAST
    LOAD_ENV_COMMAND: module load INTEL_PARALLEL
  script: *script_template


DOCUMENTATION:
  image: appropriate/curl:latest
  stage: documentation
  tags:
    - test-ci
  script: 
    - curl -X POST -F token=${DOCUMENTATION_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/2293176/trigger/pipeline
  only:
    - experimental
